#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Troubadour Installer from Laravel Installer', '1.5.0');
$app->add(new Troubadour\Installer\Console\NewCommand);

$app->run();
